### ISSUE TITLE
nldjson no longer supported

### ISSUE THREAD

**Issue by brimwats** [kometenstaub/linked-data-helper#10]
My JSON got corrupted so I went to get a new version but it looks like they only offer SKOS or MADS, not the combined: https://id.loc.gov/download/

**Comment by kometenstaub** [comment]
See https://github.com/obsidianmd/obsidian-releases/pull/997

**Comment by kometenstaub** [comment]
The new format should probably be jsonld. Since MADS and SKOS are not together anymore and some info was only available with MADS, probably MADS alone needs to be used, but the keys will be different in that case.

**Comment by kometenstaub** [comment]
From bubonicfred on Discord: https://listserv.loc.gov/cgi-bin/wa?A2=ID;8bccd60c.2204

**Comment by kometenstaub** [comment]
The old data is still available here: https://id.loc.gov/download/lcsh.both.ndjson.zip

**Comment by brimwats** [comment]
thanks so much for all your earlier work on this!

**Comment by kometenstaub** [comment]
Moving forward, this plugin will use the MADS/RDF `jsonld` file. Before I can push out a new release, the Linked Vocabs needs to be updated first because some data representation has changed.
